-- user ids are hard coded values, be careful
-- created with mockaroo: https://www.mockaroo.com/schemas/312130, https://www.mockaroo.com/2bdd3100

insert into workout_plan (name, user_id, description) values ('Bjorn', '81b4c969-01b2-41af-bcd9-6ea1c7a04eb6', 'Burn of second degree of toe(s) (nail)');
insert into workout_plan (name, user_id, description) values ('Peggie', 'aebc95f3-c5cf-41af-82ad-6084f87c078e', 'Poisoning by other psychotropic drugs, accidental (unintentional)');
insert into workout_plan (name, user_id, description) values ('Tomaso', 'aebc95f3-c5cf-41af-82ad-6084f87c078e', 'Other dislocation of unspecified knee, subsequent encounter');
insert into workout_plan (name, user_id, description) values ('Madison', '81b4c969-01b2-41af-bcd9-6ea1c7a04eb6', 'Unspecified physeal fracture of lower end of radius, right arm, subsequent encounter for fracture with nonunion');
insert into workout_plan (name, user_id, description) values ('Annetta', '2f85c0ce-bc15-4e93-b105-71b995deda02', 'Nondisplaced fracture of trapezium [larger multangular], right wrist, initial encounter for closed fracture');
insert into workout_plan (name, user_id, description) values ('Ernest', '81b4c969-01b2-41af-bcd9-6ea1c7a04eb6', 'Nondisplaced articular fracture of head of right femur, initial encounter for open fracture type I or II');
insert into workout_plan (name, user_id, description) values ('Delmar', 'aebc95f3-c5cf-41af-82ad-6084f87c078e', 'Other injury due to other accident to other unpowered watercraft, subsequent encounter');
insert into workout_plan (name, user_id, description) values ('Denney', '81b4c969-01b2-41af-bcd9-6ea1c7a04eb6', 'Burn of second degree of scalp [any part]');
insert into workout_plan (name, user_id, description) values ('Tiffi', '81b4c969-01b2-41af-bcd9-6ea1c7a04eb6', 'Nondisplaced oblique fracture of shaft of unspecified radius, sequela');
insert into workout_plan (name, user_id, description) values ('Rock', '2ac8aa7e-efae-452b-ad4d-0acb79ed53cb', 'Greenstick fracture of shaft of unspecified ulna, subsequent encounter for fracture with nonunion');
insert into workout_plan (name, user_id, description) values ('Nikki', 'aebc95f3-c5cf-41af-82ad-6084f87c078e', 'Laceration with foreign body of unspecified hand, subsequent encounter');
insert into workout_plan (name, user_id, description) values ('Annadiana', '2f85c0ce-bc15-4e93-b105-71b995deda02', 'Valgus deformity, not elsewhere classified, left elbow');
insert into workout_plan (name, user_id, description) values ('Homere', 'aebc95f3-c5cf-41af-82ad-6084f87c078e', 'Unspecified disorder of vestibular function, left ear');
insert into workout_plan (name, user_id, description) values ('Saul', '2ac8aa7e-efae-452b-ad4d-0acb79ed53cb', 'Toxic effect of unspecified organic solvent, assault, sequela');
insert into workout_plan (name, user_id, description) values ('Salvidor', 'aebc95f3-c5cf-41af-82ad-6084f87c078e', 'Person injured in collision between other motor vehicle and two- or three-wheeled motor vehicle, nontraffic');
insert into workout_plan (name, user_id, description) values ('Addy', '2f85c0ce-bc15-4e93-b105-71b995deda02', 'Complete traumatic metacarpophalangeal amputation of other finger, subsequent encounter');
insert into workout_plan (name, user_id, description) values ('Shauna', '81b4c969-01b2-41af-bcd9-6ea1c7a04eb6', 'Mittelschmerz');
insert into workout_plan (name, user_id, description) values ('Salvatore', '2f85c0ce-bc15-4e93-b105-71b995deda02', 'Poisoning by carbonic-anhydrase inhibitors, benzothiadiazides and other diuretics, assault, subsequent encounter');
insert into workout_plan (name, user_id, description) values ('Adelbert', 'aebc95f3-c5cf-41af-82ad-6084f87c078e', 'Poisoning by pyrazolone derivatives, assault, sequela');
insert into workout_plan (name, user_id, description) values ('Tito', '2ac8aa7e-efae-452b-ad4d-0acb79ed53cb', 'Burn of third degree of female genital region, initial encounter');
insert into workout_plan (name, user_id, description) values ('Heindrick', '2ac8aa7e-efae-452b-ad4d-0acb79ed53cb', 'Other secondary scoliosis');
insert into workout_plan (name, user_id, description) values ('Stepha', 'aebc95f3-c5cf-41af-82ad-6084f87c078e', 'Unspecified injury of extensor muscle, fascia and tendon of right index finger at wrist and hand level, subsequent encounter');
insert into workout_plan (name, user_id, description) values ('Carine', '2f85c0ce-bc15-4e93-b105-71b995deda02', 'Nondisplaced spiral fracture of shaft of radius, unspecified arm, subsequent encounter for closed fracture with routine healing');
insert into workout_plan (name, user_id, description) values ('Prentiss', '2ac8aa7e-efae-452b-ad4d-0acb79ed53cb', 'Toxic effect of manganese and its compounds, intentional self-harm');
insert into workout_plan (name, user_id, description) values ('Otha', '2f85c0ce-bc15-4e93-b105-71b995deda02', 'Premature rupture of membranes, onset of labor more than 24 hours following rupture');
insert into workout_plan (name, user_id, description) values ('Blane', '2ac8aa7e-efae-452b-ad4d-0acb79ed53cb', 'Thoracoabdominal aortic aneurysm, without rupture');
insert into workout_plan (name, user_id, description) values ('Sheila', '81b4c969-01b2-41af-bcd9-6ea1c7a04eb6', 'Strain of intrinsic muscle, fascia and tendon of right thumb at wrist and hand level, subsequent encounter');
insert into workout_plan (name, user_id, description) values ('Royal', '81b4c969-01b2-41af-bcd9-6ea1c7a04eb6', 'Idiopathic progressive neuropathy');
insert into workout_plan (name, user_id, description) values ('Ulrika', '2f85c0ce-bc15-4e93-b105-71b995deda02', 'Pregnancy with inconclusive fetal viability, fetus 4');
insert into workout_plan (name, user_id, description) values ('Trumann', '81b4c969-01b2-41af-bcd9-6ea1c7a04eb6', 'Other interstitial and deep keratitis, bilateral');
insert into workout_plan (name, user_id, description) values ('Cinderella', 'aebc95f3-c5cf-41af-82ad-6084f87c078e', 'Intentional self-harm by other hot fluids');
insert into workout_plan (name, user_id, description) values ('Daisi', '2ac8aa7e-efae-452b-ad4d-0acb79ed53cb', 'Pedestrian on skateboard injured in collision with heavy transport vehicle or bus in traffic accident, sequela');
insert into workout_plan (name, user_id, description) values ('Killie', '81b4c969-01b2-41af-bcd9-6ea1c7a04eb6', 'Complete traumatic metacarpophalangeal amputation of unspecified thumb, subsequent encounter');
insert into workout_plan (name, user_id, description) values ('Virgilio', '2f85c0ce-bc15-4e93-b105-71b995deda02', 'Military operations involving explosion of aerial bomb, civilian, sequela');
insert into workout_plan (name, user_id, description) values ('Lotta', '2ac8aa7e-efae-452b-ad4d-0acb79ed53cb', 'Incomplete atypical femoral fracture, left leg, subsequent encounter for fracture with malunion');
insert into workout_plan (name, user_id, description) values ('Angel', '2f85c0ce-bc15-4e93-b105-71b995deda02', 'Tachypnea, not elsewhere classified');
insert into workout_plan (name, user_id, description) values ('Cindra', '2f85c0ce-bc15-4e93-b105-71b995deda02', 'Passenger in heavy transport vehicle injured in noncollision transport accident in nontraffic accident, sequela');
insert into workout_plan (name, user_id, description) values ('Stacy', 'aebc95f3-c5cf-41af-82ad-6084f87c078e', 'Poisoning by, adverse effect of and underdosing of antineoplastic and immunosuppressive drugs');
insert into workout_plan (name, user_id, description) values ('Billie', '2ac8aa7e-efae-452b-ad4d-0acb79ed53cb', 'Nondisplaced comminuted fracture of right patella, subsequent encounter for closed fracture with routine healing');
insert into workout_plan (name, user_id, description) values ('Nikolia', 'aebc95f3-c5cf-41af-82ad-6084f87c078e', 'Poisoning by unspecified psychotropic drug, intentional self-harm');
insert into workout_plan (name, user_id, description) values ('Emmeline', '81b4c969-01b2-41af-bcd9-6ea1c7a04eb6', 'Salter-Harris Type IV physeal fracture of phalanx of unspecified toe');
insert into workout_plan (name, user_id, description) values ('Bendite', 'aebc95f3-c5cf-41af-82ad-6084f87c078e', 'Burn of third degree of unspecified elbow, subsequent encounter');
insert into workout_plan (name, user_id, description) values ('Carmelle', '2ac8aa7e-efae-452b-ad4d-0acb79ed53cb', 'Other injury of extensor muscle, fascia and tendon of right index finger at forearm level, sequela');
insert into workout_plan (name, user_id, description) values ('Marty', '81b4c969-01b2-41af-bcd9-6ea1c7a04eb6', 'Other sleep disorders not due to a substance or known physiological condition');
insert into workout_plan (name, user_id, description) values ('Lewie', 'aebc95f3-c5cf-41af-82ad-6084f87c078e', 'Flatback syndrome, lumbosacral region');
insert into workout_plan (name, user_id, description) values ('Sayres', '2ac8aa7e-efae-452b-ad4d-0acb79ed53cb', 'Chondromalacia, right shoulder');
insert into workout_plan (name, user_id, description) values ('Arielle', '81b4c969-01b2-41af-bcd9-6ea1c7a04eb6', 'Human T-cell lymphotrophic virus, type II [HTLV-II] as the cause of diseases classified elsewhere');
insert into workout_plan (name, user_id, description) values ('Manuel', '2f85c0ce-bc15-4e93-b105-71b995deda02', 'Poisoning by other fibrinolysis-affecting drugs, undetermined, initial encounter');
insert into workout_plan (name, user_id, description) values ('Aveline', 'aebc95f3-c5cf-41af-82ad-6084f87c078e', 'Car passenger injured in collision with pedestrian or animal in nontraffic accident');
insert into workout_plan (name, user_id, description) values ('Lavinia', '81b4c969-01b2-41af-bcd9-6ea1c7a04eb6', 'Retinopathy of prematurity, stage 5, left eye');
insert into workout_plan (name, user_id, description) values ('Somerset', 'aebc95f3-c5cf-41af-82ad-6084f87c078e', 'Nondisplaced fracture of coronoid process of left ulna, subsequent encounter for open fracture type I or II with malunion');
insert into workout_plan (name, user_id, description) values ('Maureen', 'aebc95f3-c5cf-41af-82ad-6084f87c078e', 'Unspecified motorcycle rider injured in collision with pedestrian or animal in nontraffic accident, initial encounter');
insert into workout_plan (name, user_id, description) values ('Will', '2f85c0ce-bc15-4e93-b105-71b995deda02', 'Corrosion of unspecified degree of multiple sites of left wrist and hand, initial encounter');
insert into workout_plan (name, user_id, description) values ('Andree', '81b4c969-01b2-41af-bcd9-6ea1c7a04eb6', 'Occupant of animal-drawn vehicle injured in other transport accident');
insert into workout_plan (name, user_id, description) values ('Dyanne', 'aebc95f3-c5cf-41af-82ad-6084f87c078e', 'Nondisplaced apophyseal fracture of right femur, initial encounter for open fracture type IIIA, IIIB, or IIIC');
insert into workout_plan (name, user_id, description) values ('Garner', '2f85c0ce-bc15-4e93-b105-71b995deda02', 'Neurogenic bowel, not elsewhere classified');
insert into workout_plan (name, user_id, description) values ('Nari', 'aebc95f3-c5cf-41af-82ad-6084f87c078e', 'High risk sexual behavior');
insert into workout_plan (name, user_id, description) values ('Roseanna', '81b4c969-01b2-41af-bcd9-6ea1c7a04eb6', 'Crushed by crocodile, initial encounter');
insert into workout_plan (name, user_id, description) values ('Maxim', '81b4c969-01b2-41af-bcd9-6ea1c7a04eb6', 'Peripheral pterygium, stationary, unspecified eye');
insert into workout_plan (name, user_id, description) values ('Netti', '2f85c0ce-bc15-4e93-b105-71b995deda02', 'Hyperemesis gravidarum with metabolic disturbance');
insert into workout_plan (name, user_id, description) values ('Graham', 'aebc95f3-c5cf-41af-82ad-6084f87c078e', 'Glaucoma with increased episcleral venous pressure, right eye');
insert into workout_plan (name, user_id, description) values ('Odetta', '2f85c0ce-bc15-4e93-b105-71b995deda02', 'Explosion and rupture of unspecified gas cylinder, subsequent encounter');
insert into workout_plan (name, user_id, description) values ('Carolann', '2f85c0ce-bc15-4e93-b105-71b995deda02', 'Other benign neoplasm of skin of left upper limb, including shoulder');
insert into workout_plan (name, user_id, description) values ('Orran', 'aebc95f3-c5cf-41af-82ad-6084f87c078e', 'Other specified crystal arthropathies, ankle and foot');
insert into workout_plan (name, user_id, description) values ('Roanne', '2f85c0ce-bc15-4e93-b105-71b995deda02', 'Other secondary gout, unspecified hand');
insert into workout_plan (name, user_id, description) values ('Justin', '2f85c0ce-bc15-4e93-b105-71b995deda02', 'Dislocation of right acromioclavicular joint, greater than 200% displacement');
insert into workout_plan (name, user_id, description) values ('Curry', '2f85c0ce-bc15-4e93-b105-71b995deda02', 'Obstetric embolism');
insert into workout_plan (name, user_id, description) values ('Allis', '2f85c0ce-bc15-4e93-b105-71b995deda02', 'Burn of unspecified degree of multiple sites of head, face, and neck, sequela');
insert into workout_plan (name, user_id, description) values ('Luise', '81b4c969-01b2-41af-bcd9-6ea1c7a04eb6', 'Burn of third degree of left foot');
insert into workout_plan (name, user_id, description) values ('Pernell', '2ac8aa7e-efae-452b-ad4d-0acb79ed53cb', 'Contusion of left index finger with damage to nail, sequela');
insert into workout_plan (name, user_id, description) values ('Coretta', '2ac8aa7e-efae-452b-ad4d-0acb79ed53cb', 'Corrosion of third degree of upper back, initial encounter');
insert into workout_plan (name, user_id, description) values ('Christiana', '2ac8aa7e-efae-452b-ad4d-0acb79ed53cb', 'Displaced fracture of triquetrum [cuneiform] bone, unspecified wrist, subsequent encounter for fracture with nonunion');
insert into workout_plan (name, user_id, description) values ('Caddric', '2f85c0ce-bc15-4e93-b105-71b995deda02', 'Nondisplaced bimalleolar fracture of unspecified lower leg, initial encounter for closed fracture');
insert into workout_plan (name, user_id, description) values ('Mathe', 'aebc95f3-c5cf-41af-82ad-6084f87c078e', 'Atherosclerosis of other type of bypass graft(s) of the left leg with ulceration of unspecified site');
insert into workout_plan (name, user_id, description) values ('Katherine', '2f85c0ce-bc15-4e93-b105-71b995deda02', 'Laceration of spleen');
insert into workout_plan (name, user_id, description) values ('Shirlene', 'aebc95f3-c5cf-41af-82ad-6084f87c078e', 'Corrosion of first degree of left scapular region, sequela');
insert into workout_plan (name, user_id, description) values ('Anna', 'aebc95f3-c5cf-41af-82ad-6084f87c078e', 'Unstable burst fracture of second thoracic vertebra, initial encounter for open fracture');
insert into workout_plan (name, user_id, description) values ('Jan', '2f85c0ce-bc15-4e93-b105-71b995deda02', 'Rheumatoid nodule, unspecified shoulder');
insert into workout_plan (name, user_id, description) values ('Bronnie', '2f85c0ce-bc15-4e93-b105-71b995deda02', 'Posterior corneal pigmentations');
insert into workout_plan (name, user_id, description) values ('Wilhelmina', '2ac8aa7e-efae-452b-ad4d-0acb79ed53cb', 'Corrosion of second degree of left thigh, sequela');
insert into workout_plan (name, user_id, description) values ('Kimbell', '2f85c0ce-bc15-4e93-b105-71b995deda02', 'Laceration without foreign body of abdominal wall, periumbilic region without penetration into peritoneal cavity');
insert into workout_plan (name, user_id, description) values ('Demetria', 'aebc95f3-c5cf-41af-82ad-6084f87c078e', 'Other osteonecrosis, unspecified ankle');
insert into workout_plan (name, user_id, description) values ('Stormy', '2ac8aa7e-efae-452b-ad4d-0acb79ed53cb', 'Unspecified convulsions');
insert into workout_plan (name, user_id, description) values ('Van', '81b4c969-01b2-41af-bcd9-6ea1c7a04eb6', 'Other sprain of unspecified foot');
insert into workout_plan (name, user_id, description) values ('Hubey', '81b4c969-01b2-41af-bcd9-6ea1c7a04eb6', 'Unspecified injury of muscle, fascia and tendon of the posterior muscle group at thigh level, left thigh, subsequent encounter');
insert into workout_plan (name, user_id, description) values ('Astra', '2f85c0ce-bc15-4e93-b105-71b995deda02', 'Sprain of metacarpophalangeal joint of right ring finger, subsequent encounter');
insert into workout_plan (name, user_id, description) values ('Heywood', '81b4c969-01b2-41af-bcd9-6ea1c7a04eb6', 'Unspecified intracapsular fracture of right femur, subsequent encounter for open fracture type IIIA, IIIB, or IIIC with nonunion');
insert into workout_plan (name, user_id, description) values ('Erica', '81b4c969-01b2-41af-bcd9-6ea1c7a04eb6', 'Infection and inflammatory reaction due to internal fixation device of right femur');
insert into workout_plan (name, user_id, description) values ('Bartlet', '2f85c0ce-bc15-4e93-b105-71b995deda02', 'Other musculoskeletal tuberculosis');
insert into workout_plan (name, user_id, description) values ('Rozella', '2ac8aa7e-efae-452b-ad4d-0acb79ed53cb', 'War operations involving direct blast effect of nuclear weapon, military personnel');
insert into workout_plan (name, user_id, description) values ('Wolfie', '2ac8aa7e-efae-452b-ad4d-0acb79ed53cb', 'Obstruction of duodenum');
insert into workout_plan (name, user_id, description) values ('Ainslie', '81b4c969-01b2-41af-bcd9-6ea1c7a04eb6', 'Desquamative interstitial pneumonia');
insert into workout_plan (name, user_id, description) values ('Patty', '2f85c0ce-bc15-4e93-b105-71b995deda02', 'Displaced transverse fracture of shaft of humerus, left arm, subsequent encounter for fracture with routine healing');
insert into workout_plan (name, user_id, description) values ('Nicky', '2f85c0ce-bc15-4e93-b105-71b995deda02', 'Juvenile idiopathic scoliosis, cervicothoracic region');
insert into workout_plan (name, user_id, description) values ('Kelley', '81b4c969-01b2-41af-bcd9-6ea1c7a04eb6', 'Displaced supracondylar fracture with intracondylar extension of lower end of unspecified femur, subsequent encounter for open fracture type IIIA, IIIB, or IIIC with nonunion');
insert into workout_plan (name, user_id, description) values ('Daisey', '2f85c0ce-bc15-4e93-b105-71b995deda02', 'Other secondary osteonecrosis, right femur');
insert into workout_plan (name, user_id, description) values ('Yancy', '81b4c969-01b2-41af-bcd9-6ea1c7a04eb6', 'Infections of cervix in pregnancy, third trimester');
insert into workout_plan (name, user_id, description) values ('Ignace', '81b4c969-01b2-41af-bcd9-6ea1c7a04eb6', 'Erosion of other implanted mesh to organ or tissue, subsequent encounter');
insert into workout_plan (name, user_id, description) values ('Clemence', '81b4c969-01b2-41af-bcd9-6ea1c7a04eb6', 'Sprain of hip');
insert into workout_plan (name, user_id, description) values ('Idette', '2ac8aa7e-efae-452b-ad4d-0acb79ed53cb', 'Traumatic rupture of other ligament of right middle finger at metacarpophalangeal and interphalangeal joint, initial encounter');
insert into workout_plan (name, user_id, description) values ('Klara', 'aebc95f3-c5cf-41af-82ad-6084f87c078e', 'Sick sinus syndrome');
insert into workout_plan (name, user_id, description) values ('Laurel', '2ac8aa7e-efae-452b-ad4d-0acb79ed53cb', 'Traumatic rupture of volar plate of right index finger at metacarpophalangeal and interphalangeal joint, initial encounter');
insert into workout_plan (name, user_id, description) values ('Lonni', '81b4c969-01b2-41af-bcd9-6ea1c7a04eb6', 'Contusion of oral cavity, sequela');
insert into workout_plan (name, user_id, description) values ('Dannel', 'aebc95f3-c5cf-41af-82ad-6084f87c078e', 'Poisoning by anthelminthics, intentional self-harm, subsequent encounter');
insert into workout_plan (name, user_id, description) values ('Arty', '2ac8aa7e-efae-452b-ad4d-0acb79ed53cb', 'Rheumatoid vasculitis with rheumatoid arthritis of hand');
insert into workout_plan (name, user_id, description) values ('Lisabeth', 'aebc95f3-c5cf-41af-82ad-6084f87c078e', 'Person injured while boarding or alighting from railway train or railway vehicle, sequela');
insert into workout_plan (name, user_id, description) values ('Marcella', '2f85c0ce-bc15-4e93-b105-71b995deda02', 'Poisoning by, adverse effect of and underdosing of butyrophenone and thiothixene neuroleptics');
insert into workout_plan (name, user_id, description) values ('Kile', '81b4c969-01b2-41af-bcd9-6ea1c7a04eb6', 'Transient synovitis, other site');
insert into workout_plan (name, user_id, description) values ('Nedda', '2f85c0ce-bc15-4e93-b105-71b995deda02', 'Other disorders of continuity of bone, left tibia');
insert into workout_plan (name, user_id, description) values ('Neila', '81b4c969-01b2-41af-bcd9-6ea1c7a04eb6', 'Frostbite with tissue necrosis of hand');
insert into workout_plan (name, user_id, description) values ('Petr', '81b4c969-01b2-41af-bcd9-6ea1c7a04eb6', 'Diffuse traumatic brain injury with loss of consciousness of 6 hours to 24 hours, initial encounter');
insert into workout_plan (name, user_id, description) values ('Rita', '2ac8aa7e-efae-452b-ad4d-0acb79ed53cb', 'Unspecified pedal cyclist injured in collision with other motor vehicles in traffic accident, sequela');
insert into workout_plan (name, user_id, description) values ('Ernestine', '2ac8aa7e-efae-452b-ad4d-0acb79ed53cb', 'Metabolic encephalopathy');
insert into workout_plan (name, user_id, description) values ('Florinda', '2ac8aa7e-efae-452b-ad4d-0acb79ed53cb', 'Strain of unspecified muscle, fascia and tendon at shoulder and upper arm level, left arm, subsequent encounter');
insert into workout_plan (name, user_id, description) values ('Audi', '2ac8aa7e-efae-452b-ad4d-0acb79ed53cb', 'Military operation involving nuclear radiation effects of nuclear weapon, civilian');
insert into workout_plan (name, user_id, description) values ('Conny', 'aebc95f3-c5cf-41af-82ad-6084f87c078e', 'Partial traumatic amputation at unspecified shoulder joint, initial encounter');
insert into workout_plan (name, user_id, description) values ('Hamnet', '2ac8aa7e-efae-452b-ad4d-0acb79ed53cb', 'Unspecified open wound of other finger without damage to nail');
insert into workout_plan (name, user_id, description) values ('Livvyy', '2ac8aa7e-efae-452b-ad4d-0acb79ed53cb', 'Poisoning by, adverse effect of and underdosing of other bacterial vaccines');
insert into workout_plan (name, user_id, description) values ('Mathilde', 'aebc95f3-c5cf-41af-82ad-6084f87c078e', 'Non-pressure chronic ulcer of left ankle with unspecified severity');
insert into workout_plan (name, user_id, description) values ('Leah', '2f85c0ce-bc15-4e93-b105-71b995deda02', 'Struck by falling object on other powered watercraft, initial encounter');
insert into workout_plan (name, user_id, description) values ('Claudell', 'aebc95f3-c5cf-41af-82ad-6084f87c078e', 'Unspecified physeal fracture of upper end of unspecified tibia');
insert into workout_plan (name, user_id, description) values ('Justino', '2ac8aa7e-efae-452b-ad4d-0acb79ed53cb', 'Adverse effect of other parasympathomimetics [cholinergics], subsequent encounter');
insert into workout_plan (name, user_id, description) values ('Friedrich', '2ac8aa7e-efae-452b-ad4d-0acb79ed53cb', 'Nondisplaced Maisonneuve''s fracture of unspecified leg, subsequent encounter for closed fracture with malunion');
insert into workout_plan (name, user_id, description) values ('Ulises', '81b4c969-01b2-41af-bcd9-6ea1c7a04eb6', 'Toxic effect of venom of other reptiles, accidental (unintentional), subsequent encounter');
insert into workout_plan (name, user_id, description) values ('Terrye', 'aebc95f3-c5cf-41af-82ad-6084f87c078e', 'Poisoning by antifungal antibiotics, systemically used, undetermined, subsequent encounter');
insert into workout_plan (name, user_id, description) values ('Corrie', 'aebc95f3-c5cf-41af-82ad-6084f87c078e', 'Sprain of sternoclavicular (joint) (ligament)');
insert into workout_plan (name, user_id, description) values ('Gib', '2ac8aa7e-efae-452b-ad4d-0acb79ed53cb', 'Burn of unspecified degree of back of left hand, subsequent encounter');
insert into workout_plan (name, user_id, description) values ('Angelika', '81b4c969-01b2-41af-bcd9-6ea1c7a04eb6', 'Injury of left uterine artery, initial encounter');
insert into workout_plan (name, user_id, description) values ('Oran', '2f85c0ce-bc15-4e93-b105-71b995deda02', 'Barton''s fracture of right radius, subsequent encounter for closed fracture with delayed healing');
insert into workout_plan (name, user_id, description) values ('Raven', '2ac8aa7e-efae-452b-ad4d-0acb79ed53cb', 'Unspecified fracture of lower end of left femur, subsequent encounter for open fracture type IIIA, IIIB, or IIIC with delayed healing');
insert into workout_plan (name, user_id, description) values ('Michail', '2ac8aa7e-efae-452b-ad4d-0acb79ed53cb', 'Other nondisplaced fracture of base of first metacarpal bone, right hand, subsequent encounter for fracture with delayed healing');
insert into workout_plan (name, user_id, description) values ('Boote', 'aebc95f3-c5cf-41af-82ad-6084f87c078e', 'Contusion of great toe without damage to nail');
insert into workout_plan (name, user_id, description) values ('Samantha', '2ac8aa7e-efae-452b-ad4d-0acb79ed53cb', 'Subluxation of unspecified interphalangeal joint of right ring finger');
insert into workout_plan (name, user_id, description) values ('Eustacia', '81b4c969-01b2-41af-bcd9-6ea1c7a04eb6', 'Nondisplaced spiral fracture of shaft of ulna, left arm, subsequent encounter for open fracture type I or II with malunion');
insert into workout_plan (name, user_id, description) values ('Catarina', '2f85c0ce-bc15-4e93-b105-71b995deda02', 'Displaced fracture of olecranon process without intraarticular extension of right ulna, subsequent encounter for open fracture type IIIA, IIIB, or IIIC with nonunion');
insert into workout_plan (name, user_id, description) values ('Oona', '2f85c0ce-bc15-4e93-b105-71b995deda02', 'Contact with blunt object, undetermined intent, initial encounter');
insert into workout_plan (name, user_id, description) values ('Luigi', 'aebc95f3-c5cf-41af-82ad-6084f87c078e', 'Unspecified physeal fracture of lower end of ulna, left arm, subsequent encounter for fracture with routine healing');
insert into workout_plan (name, user_id, description) values ('Eudora', 'aebc95f3-c5cf-41af-82ad-6084f87c078e', 'Injury of other nerves at wrist and hand level of right arm, sequela');
insert into workout_plan (name, user_id, description) values ('Rockey', '81b4c969-01b2-41af-bcd9-6ea1c7a04eb6', 'Infection and inflammatory reaction due to other internal orthopedic prosthetic devices, implants and grafts');
insert into workout_plan (name, user_id, description) values ('Cobby', '81b4c969-01b2-41af-bcd9-6ea1c7a04eb6', 'War operations involving intentional restriction of air and airway, military personnel, sequela');
insert into workout_plan (name, user_id, description) values ('Lesley', 'aebc95f3-c5cf-41af-82ad-6084f87c078e', 'Injury of acoustic nerve, left side, subsequent encounter');
insert into workout_plan (name, user_id, description) values ('Der', 'aebc95f3-c5cf-41af-82ad-6084f87c078e', 'Nondisplaced fracture of anterior process of left calcaneus, initial encounter for closed fracture');
insert into workout_plan (name, user_id, description) values ('Dollie', '2ac8aa7e-efae-452b-ad4d-0acb79ed53cb', 'Laceration of right renal artery');
insert into workout_plan (name, user_id, description) values ('Everard', '81b4c969-01b2-41af-bcd9-6ea1c7a04eb6', 'Exposure to (parental) (environmental) tobacco smoke in the perinatal period');
insert into workout_plan (name, user_id, description) values ('Sheeree', '2ac8aa7e-efae-452b-ad4d-0acb79ed53cb', 'Dislocation of distal interphalangeal joint of right middle finger, subsequent encounter');
insert into workout_plan (name, user_id, description) values ('Gilberte', '81b4c969-01b2-41af-bcd9-6ea1c7a04eb6', 'Other viral infections of unspecified site');
insert into workout_plan (name, user_id, description) values ('Dennis', '2f85c0ce-bc15-4e93-b105-71b995deda02', 'Macular corneal dystrophy');
insert into workout_plan (name, user_id, description) values ('Kial', '2f85c0ce-bc15-4e93-b105-71b995deda02', 'Unstable burst fracture of T9-T10 vertebra, subsequent encounter for fracture with delayed healing');
insert into workout_plan (name, user_id, description) values ('Locke', '2ac8aa7e-efae-452b-ad4d-0acb79ed53cb', 'Monoplegia of lower limb following nontraumatic subarachnoid hemorrhage');
insert into workout_plan (name, user_id, description) values ('Reggie', '2ac8aa7e-efae-452b-ad4d-0acb79ed53cb', 'Person on outside of pick-up truck or van injured in collision with heavy transport vehicle or bus in nontraffic accident, subsequent encounter');
insert into workout_plan (name, user_id, description) values ('Kris', '2ac8aa7e-efae-452b-ad4d-0acb79ed53cb', 'Unspecified fracture of lower end of right tibia, subsequent encounter for open fracture type I or II with nonunion');
insert into workout_plan (name, user_id, description) values ('Cloe', '2ac8aa7e-efae-452b-ad4d-0acb79ed53cb', 'Crushing injury of right hip, initial encounter');
insert into workout_plan (name, user_id, description) values ('Kermy', '81b4c969-01b2-41af-bcd9-6ea1c7a04eb6', 'Intentional self-harm by other hot fluids, subsequent encounter');
insert into workout_plan (name, user_id, description) values ('Andie', '81b4c969-01b2-41af-bcd9-6ea1c7a04eb6', 'Other fracture of left femur, sequela');
insert into workout_plan (name, user_id, description) values ('Ninnetta', 'aebc95f3-c5cf-41af-82ad-6084f87c078e', 'Unspecified open wound, left knee, subsequent encounter');
insert into workout_plan (name, user_id, description) values ('Laryssa', '2f85c0ce-bc15-4e93-b105-71b995deda02', 'Passenger in pick-up truck or van injured in noncollision transport accident in traffic accident, initial encounter');
insert into workout_plan (name, user_id, description) values ('Andree', '2ac8aa7e-efae-452b-ad4d-0acb79ed53cb', 'Other specified extrapyramidal and movement disorders');
insert into workout_plan (name, user_id, description) values ('Othella', '2ac8aa7e-efae-452b-ad4d-0acb79ed53cb', 'Intestinal bypass and anastomosis status');
insert into workout_plan (name, user_id, description) values ('Chevalier', '2f85c0ce-bc15-4e93-b105-71b995deda02', 'Malignant neoplasm of duodenum');
insert into workout_plan (name, user_id, description) values ('Joline', '2ac8aa7e-efae-452b-ad4d-0acb79ed53cb', 'Corrosion of unspecified degree of right knee, initial encounter');
insert into workout_plan (name, user_id, description) values ('Carolyn', '2ac8aa7e-efae-452b-ad4d-0acb79ed53cb', 'Injury of unspecified nerves at abdomen, lower back and pelvis level, initial encounter');
insert into workout_plan (name, user_id, description) values ('Konstance', 'aebc95f3-c5cf-41af-82ad-6084f87c078e', 'Unspecified car occupant injured in collision with car, pick-up truck or van in nontraffic accident');
insert into workout_plan (name, user_id, description) values ('Ronald', 'aebc95f3-c5cf-41af-82ad-6084f87c078e', 'Poisoning by antiparkinsonism drugs and other central muscle-tone depressants, undetermined, sequela');
insert into workout_plan (name, user_id, description) values ('Stephenie', 'aebc95f3-c5cf-41af-82ad-6084f87c078e', 'Dislocation of midcarpal joint of unspecified wrist');
insert into workout_plan (name, user_id, description) values ('Dari', '81b4c969-01b2-41af-bcd9-6ea1c7a04eb6', 'Nondisplaced Zone III fracture of sacrum, subsequent encounter for fracture with delayed healing');
insert into workout_plan (name, user_id, description) values ('Raimund', '2ac8aa7e-efae-452b-ad4d-0acb79ed53cb', 'Brown-Sequard syndrome at T1 level of thoracic spinal cord');
insert into workout_plan (name, user_id, description) values ('Alden', '2f85c0ce-bc15-4e93-b105-71b995deda02', 'Cleft lip, bilateral');
insert into workout_plan (name, user_id, description) values ('Bentlee', '2ac8aa7e-efae-452b-ad4d-0acb79ed53cb', 'Legal intervention involving unspecified sharp objects, law enforcement official injured, initial encounter');
insert into workout_plan (name, user_id, description) values ('Kincaid', '2ac8aa7e-efae-452b-ad4d-0acb79ed53cb', 'Burn of second degree of right wrist');
insert into workout_plan (name, user_id, description) values ('Coleman', '2ac8aa7e-efae-452b-ad4d-0acb79ed53cb', 'Other specified arthritis, unspecified ankle and foot');
insert into workout_plan (name, user_id, description) values ('Gwyneth', '2ac8aa7e-efae-452b-ad4d-0acb79ed53cb', 'Other personality and behavioral disorders due to known physiological condition');
insert into workout_plan (name, user_id, description) values ('Sigfrid', '2f85c0ce-bc15-4e93-b105-71b995deda02', 'Burn of first degree of unspecified upper arm, initial encounter');
insert into workout_plan (name, user_id, description) values ('Allyn', 'aebc95f3-c5cf-41af-82ad-6084f87c078e', 'Contusion of hand');
insert into workout_plan (name, user_id, description) values ('Lovell', '81b4c969-01b2-41af-bcd9-6ea1c7a04eb6', 'Embolism due to internal orthopedic prosthetic devices, implants and grafts, sequela');
insert into workout_plan (name, user_id, description) values ('Rhody', '81b4c969-01b2-41af-bcd9-6ea1c7a04eb6', 'Bathroom in children''s home and orphanage as the place of occurrence of the external cause');
insert into workout_plan (name, user_id, description) values ('Hesther', '81b4c969-01b2-41af-bcd9-6ea1c7a04eb6', 'Tinea cruris');
insert into workout_plan (name, user_id, description) values ('Maude', '81b4c969-01b2-41af-bcd9-6ea1c7a04eb6', 'Unspecified fracture of shaft of right femur, subsequent encounter for open fracture type I or II with routine healing');
insert into workout_plan (name, user_id, description) values ('Klaus', '2ac8aa7e-efae-452b-ad4d-0acb79ed53cb', 'Displaced fracture of shaft of second metacarpal bone, left hand');
insert into workout_plan (name, user_id, description) values ('Therine', '2f85c0ce-bc15-4e93-b105-71b995deda02', 'Laceration of unspecified blood vessel at ankle and foot level, unspecified leg, subsequent encounter');
insert into workout_plan (name, user_id, description) values ('Anett', 'aebc95f3-c5cf-41af-82ad-6084f87c078e', 'Personal history of in-situ neoplasm of cervix uteri');
insert into workout_plan (name, user_id, description) values ('Susie', '2f85c0ce-bc15-4e93-b105-71b995deda02', 'Vibratory urticaria');
insert into workout_plan (name, user_id, description) values ('Arney', '2ac8aa7e-efae-452b-ad4d-0acb79ed53cb', 'Cerebral infarction due to embolism of unspecified cerebellar artery');
insert into workout_plan (name, user_id, description) values ('Marcy', '81b4c969-01b2-41af-bcd9-6ea1c7a04eb6', 'Other and unspecified metabolic disorders');
insert into workout_plan (name, user_id, description) values ('Jaquith', 'aebc95f3-c5cf-41af-82ad-6084f87c078e', 'Minor laceration of right pulmonary blood vessels, subsequent encounter');
insert into workout_plan (name, user_id, description) values ('Melanie', '2f85c0ce-bc15-4e93-b105-71b995deda02', 'Other intraarticular fracture of lower end of right radius, subsequent encounter for open fracture type I or II with routine healing');
insert into workout_plan (name, user_id, description) values ('Nolana', '2f85c0ce-bc15-4e93-b105-71b995deda02', 'War operations involving explosion of aerial bomb, military personnel, initial encounter');
insert into workout_plan (name, user_id, description) values ('Waite', '2ac8aa7e-efae-452b-ad4d-0acb79ed53cb', 'Unspecified injury of unspecified blood vessel at hip and thigh level, left leg, subsequent encounter');
insert into workout_plan (name, user_id, description) values ('Ammamaria', 'aebc95f3-c5cf-41af-82ad-6084f87c078e', 'Complex tear of medial meniscus, current injury, right knee');
insert into workout_plan (name, user_id, description) values ('Hazlett', '2ac8aa7e-efae-452b-ad4d-0acb79ed53cb', 'Intentional self-harm by sword or dagger, initial encounter');
insert into workout_plan (name, user_id, description) values ('Lanni', '2f85c0ce-bc15-4e93-b105-71b995deda02', 'Other intervertebral disc disorders, lumbosacral region');
insert into workout_plan (name, user_id, description) values ('Donelle', '2f85c0ce-bc15-4e93-b105-71b995deda02', 'Displaced fracture of lower epiphysis (separation) of unspecified femur, subsequent encounter for open fracture type I or II with nonunion');
insert into workout_plan (name, user_id, description) values ('Beck', '2f85c0ce-bc15-4e93-b105-71b995deda02', 'Other fracture of lower end of unspecified femur, subsequent encounter for closed fracture with nonunion');
insert into workout_plan (name, user_id, description) values ('Othello', '81b4c969-01b2-41af-bcd9-6ea1c7a04eb6', 'Underdosing of electrolytic, caloric and water-balance agents, initial encounter');
insert into workout_plan (name, user_id, description) values ('Torrey', 'aebc95f3-c5cf-41af-82ad-6084f87c078e', 'Other intraoperative and postprocedural complications of the spleen');
insert into workout_plan (name, user_id, description) values ('Beckie', '81b4c969-01b2-41af-bcd9-6ea1c7a04eb6', 'Corrosion of unspecified degree of unspecified ankle, initial encounter');
insert into workout_plan (name, user_id, description) values ('Dana', 'aebc95f3-c5cf-41af-82ad-6084f87c078e', 'Displaced fracture of shaft of first metacarpal bone, unspecified hand, initial encounter for closed fracture');
insert into workout_plan (name, user_id, description) values ('Jemmy', '2f85c0ce-bc15-4e93-b105-71b995deda02', 'Unspecified psychosis not due to a substance or known physiological condition');
insert into workout_plan (name, user_id, description) values ('Amelina', '2f85c0ce-bc15-4e93-b105-71b995deda02', 'Dislocation of unspecified cervical vertebrae, subsequent encounter');
insert into workout_plan (name, user_id, description) values ('Palmer', '81b4c969-01b2-41af-bcd9-6ea1c7a04eb6', 'Sprain of other specified parts of thorax, initial encounter');
insert into workout_plan (name, user_id, description) values ('Ingemar', '2f85c0ce-bc15-4e93-b105-71b995deda02', 'HELLP syndrome, complicating childbirth');

